title: USBR RISE EDR Guide
description: Standalone, Markdown-editable documentation for using the USBR RISE OGC API - Environmental Data Retrieval endpoint.
url: "https://cgs-earth.github.io"
baseurl: "/rise-edr-docs"
repository: "cgs-earth/rise-edr-docs"

theme: null
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - script
  - .bundle
  - .github
  - node_modules
  - public
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
